version: '3'
services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:10.0.1
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/keycloak-dump.json
    volumes:
    - ./tmp/keycloak-dump.json:/tmp/keycloak-dump.json
    ports:
    - 8888:8080
